version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - PORT=3001
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
